### ISSUE TITLE
Amount of ETH earned doesn't increase when updating time horizon

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/explorer#138]
If I increase my time horizon from 1 year to 2 years, I would expect to see my forecasted eth yield increase.

**Comment by adamsoffer** [comment]
Related bug...time horizon displays 0 rounds.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/555740/174128461-d77a76fd-e449-40ad-a99b-c757b0c83576.png">

**Comment by 0xcadams** [comment]
Very good catch!!
