### ISSUE TITLE
Deploy Nitro compatible explorer for mainnet

### ISSUE THREAD

**Issue by yondonfu** [livepeer/explorer#169]

**Comment by yondonfu** [comment]
From @adamsoffer:

> Yeah, the plan is to deploy when the downtime begins with wallet connections temporarily paused along with a banner announcement explaining why in order to prevent txs from being submitted (this is implemented already on beta.explorer.livepeer.org and ready to be deployed as soon as downtime begins). We will reenable wallet connections when the downtime ends.

**Comment by adamsoffer** [comment]
@yondonfu Nitro support has been merged and wallet connections temporarily paused on the explorer.
