### ISSUE TITLE
unable to claim or update orchestrator page after hang on save

### ISSUE THREAD

**Issue by ArcAster** [livepeer/explorer#17]
Prior to the L2 migration I attempted to claim the LivePeer explorer page for my orchestrator.  All three transactions appeared to sign correctly with MetaMask, however once I had entered my desired info and clicked 'save' the LivePeer explorer page hung and crashed.  When I quit and restarted Chrome I found that my desired changes had not been applied and that the prompt to 'setup my profile' was still present.

I attempted to go through the setup process again, however whenever I tried this the dialogue showing the progress of each  signed transaction would display the first two signatures as successful and then hang on the third, crashing the app and not prompting Metamask.  This same behavior has persisted after the L2 migration.

Here is a link to my orchestrator profile -> https://explorer.livepeer.org/accounts/0x432e26fC08f236c78fD237882018a95B4c0a3D2A/orchestrating

I'm curious if it's at all possible to delete these signatures so I can try once again to claim the profile?

<img width="912" alt="Screen_Shot_2022-02-14_at_8 56 32_PM" src="https://user-images.githubusercontent.com/8689558/153994825-19882a0a-36d9-43fd-8b0b-ec1a6edd823a.png">

Here's a gif of the behavior as well, along with opening metamask.
https://imgur.com/a/sIUcsow

I've also attached a screenshot of what is displayed prior to the explorer page hanging.

Thank you!

**Comment by papabear99** [comment]
FWIW I can't change my profile info.  Most times after clicking 'Save' it just hangs.  On 2 occasions I actually got the profile to update , or at least not hang and show the new info, it reverted back after refreshing.

**Comment by stronk-dev** [comment]
Seems to be stuck on await ThreeBox.openBox in explorer/components/EditProfile/index.tsx:
```
  const onSubmit = async () => {
    const ThreeBox = require("3box");

    console.log("will open 3box @ " + context.account);
    console.log(context.library.provider);

    setSaving(true);
    const box = await ThreeBox.openBox(
      context.account,
      context.library.provider
    );
    let hash = null;

    console.log("opened 3box @ " + context.account);

    ...
```
It does make a connection but the promise openBox returns never seems to revolve:
![image](https://user-images.githubusercontent.com/9502378/155014059-6d0c6112-a0b6-47ac-a0fe-9bdab579bee8.png)
Issue persists on mainnet as well as Arbitrum.
