### ISSUE TITLE
Caching for LPT amount when migrating is stale

### ISSUE THREAD

**Issue by 0xcadams** [livepeer/explorer#177]
When migrating from L1, the LPT amount stays stale for a few minutes while the subgraph is updated. The API endpoint should be updated to have a shorter cache time to get a more recent value.

**Comment by adamsoffer** [comment]
Noting that I observed the same behavior while undelegating stake so this issue may be affecting other mutations as well.

**Comment by 0xcadams** [comment]
Fixed by https://github.com/livepeer/explorer/pull/183
