### ISSUE TITLE
Stale delegated stake displayed for orchestrator

### ISSUE THREAD

**Issue by yondonfu** [livepeer/explorer#181]
The explorer shows a stale delegated stake value for an orchestrator that is different than the value fetched directly from the BondingManager contract as well as from the subgraph.

The orchestrator in question is 0x10742714F33f3d804E3FA489618b5c3Ca12a6dF7.

The explorer at https://explorer.livepeer.org/accounts/0x10742714f33f3d804e3fa489618b5c3ca12a6df7/orchestrating

The value fetched from the BondingManager via Arbiscan https://arbiscan.io/address/0x35Bcf3c30594191d53231E4FF333E8A770453e40#readProxyContract
 
![Screen Shot 2022-09-06 at 12 39 34 PM](https://user-images.githubusercontent.com/5933273/188690520-270b7308-38d8-49f0-901c-b1631c2a2c66.png)

The value fetched from the subgraph at https://thegraph.com/hosted-service/subgraph/livepeer/arbitrum-one

![Screen Shot 2022-09-06 at 12 39 27 PM](https://user-images.githubusercontent.com/5933273/188690620-46486d7e-a86c-49de-a375-1021238515fe.png)

Additionally, the "Transactions" section in the homepage of the explorer does not show the most recent bond tx that increased the delegated stake of the orchestrator. Note: The tx was initiated by a multisig so if the explorer has issues handling txs initiated by contracts then perhaps that is related.

**Comment by yondonfu** [comment]
Update:

https://explorer.livepeer.org/accounts/0x10742714f33f3d804e3fa489618b5c3ca12a6df7/orchestrating shows the correct delegated stake now. Maybe this was the browser showing stale cached values previously?

The "Transactions" section of the homepage still does not show the bond tx.

**Comment by 0xcadams** [comment]
Fixed by https://github.com/livepeer/explorer/pull/183
