### ISSUE TITLE
Delegate button remain greyed out after transaction approval 

### ISSUE THREAD

**Issue by AuthorityNull** [livepeer/explorer#182]
Some delegators have been reporting an issue where the Delegate button remains unclickable after successful approval. The issue appears to fix itself, either after a long period of time or multiple browser restarts.

https://user-images.githubusercontent.com/95463891/189389482-a167b864-7f61-4a03-8e2e-208283251f5f.mp4

**Comment by 0xcadams** [comment]
Related to https://github.com/livepeer/explorer/issues/177

**Comment by 0xcadams** [comment]
Fixed by https://github.com/livepeer/explorer/pull/183
