### ISSUE TITLE
[bug] ENS avatars not loading for a lot of O's

### ISSUE THREAD

**Issue by stronk-dev** [livepeer/explorer#211]
NFT and IPFS avatars seem to be fine, but images hosted on 'normal' remote targets do not seem to load. Would it be possible to just load these in client side? Or would that open the explorer up to security vulnerabilities?

**Comment by 0xcadams** [comment]
This should be resolved now: https://github.com/livepeer/explorer/commit/48785f89c52a72142b4f4d578734348d240625c5
