### ISSUE TITLE
estimate earnings calculations not accurate

### ISSUE THREAD

**Issue by JJassonn69** [livepeer/explorer#29]
Problem:

I was checking the code for the projected-income box calculation for the delegators. It seems like the calculation for the projected income only takes into account of the ROI (rate of inflation), rather than the whole equation of ticket earned and the fee cuts of the orchestrator for the ticket won.

As the delegators assume that the estimated earnings is the total earnings they can expect at the current ROI, they don't consider the aspect of eth fees earned and their cut in it.

As this is the first point of contact with the delegators we should make it clear that the main change in earnings for the delegators is from eth fees (aside from reward cut which can be easily understood) which is calculated by the percentage of their stake at the node and the fee cut. (Delegators just looking at the dashboard and eth earninings from leaderboard assume they will get the eth from fees on the basis of fee cut percentage ( because it's very difficult to  wrap (one's) head around the fact that  the fee cut percentage is not the actual percentage of eth fees they will get rather its their stake amount's proportion which is a small number for delegators with less LPT to  stake with bigger O's and larger with smaller O's. 

Solution:

We should either put a banner that explains the nuances in this calculation when someone is delegating so that people are aware of the fact or build a better projected income tool that takes into account the factors that play into the calculation.

**Comment by stronk-dev** [comment]
The calculation gets done in `components/DelegatingWidget/ProjectionBox.tsx` and you are correct that it only considers the rate of inflation at this moment:
`{data.principle ? ((data.roi / +data.principle) * 100).toFixed(2) + "%"  : 0 + "%"}`

We could definitely improve this by expanding the query to also pull total stake, Eth fees earned since L2 migration and the Fee commission as well, and then make a guesstimate based on how much Eth fees you might gobble up by delegating to a particular O.

**Comment by JJassonn69** [comment]
`estimated earnings (E) = ((inflation percent the time (I)% * LPT being staked (L))- (orchestrator percent cut (O%) * (I%*L))) + ((L/ Orchestrator's total stake (Ot)) * 100 * ((100% - Orchestrator's fee cut (Of)) * (total value of fees earned by orchestrator in the last month(Fo)/30))`

	`Yearly APY = (estimated earnings (E) * 360) / 100%`
This should be somewhat better calculation.

**Comment by 0xcadams** [comment]
We are reworking this feature in https://github.com/livepeer/explorer/issues/85, closing this issue in favor of that. Please monitor that issue for tracking when this lands.
