### ISSUE TITLE
Explorer ETH amount refers to L1

### ISSUE THREAD

**Issue by hthillman** [livepeer/explorer#44]
Looks like we're pulling ETH balances from L1 rather than Arb

<img width="234" alt="Screen Shot 2022-02-28 at 3 37 42 PM" src="https://user-images.githubusercontent.com/35902552/156077036-4f58ca2f-ae93-4de3-88f8-01b3440a1aa6.png">

**Comment by 0xcadams** [comment]
@hthillman is this still an issue on the latest explorer?

<img width="640" alt="Screen Shot 2022-05-03 at 9 59 09 AM" src="https://user-images.githubusercontent.com/32714304/166502648-2d0d83f1-2287-4117-8e27-154dc7e85b97.png">

**Comment by 0xcadams** [comment]
Closing for now, we can reopen if this is still an issue
