### ISSUE TITLE
Show when round is locked inside the round widget

### ISSUE THREAD

**Issue by adamsoffer** [livepeer/explorer#65]
**What's the problem? (required)**
I'm unable to tell when a round is locked in the explorer.

**What's the current behavior? (required)**
The round widget displays the initialized status of the current round, but does not display whether the current round is locked.

**Describe a possible solution you've considered (optional)**
When a round is locked, display a lock icon next to text that reads "Locked" inside the round widget

**Comment by 0xcadams** [comment]
Closing in favor of https://github.com/livepeer/explorer/issues/93
