### ISSUE TITLE
Feature request: see bonds and unbonds for a particular validator

### ISSUE THREAD

**Issue by jbrukh** [livepeer/explorer#74]
**What's the problem? (required)**
Describe the problem or need in exactly 1 sentence. Ex. "I'm unable to [...]", or "I am confused by [...]"

I'm unable to easily see who bonds and unbonds (and how much) to my validator.

**What's the current behavior? (required)**
A clear and concise description of the current behavior of the DApp or package (or lack thereof).

In the current iteration, I'd need to write a script that filtered Ethereum transactions for bonds and unbonds and filter them by my validator's address.

**Do you have any personal experiences dealing with this problem? (optional)**
Describe your personal experiences related this problem in 1-4 sentences.

It's just an inconvenience and having it would increase the transparency of the system that would allow participants to make better decisions about the system.

**Describe a possible solution you've considered (optional)**

Solution 1 (Good): For each validator, list bonding and unbonding transactions in their "Recent Activity" feed.

Solution 2 (Better): Have a page which shows who the bonding addresses are and how much they are bonding, and their activity.

**Additional context (optional)**
Add any other context or screenshots about the enhancement or feature request here.

**Comment by 0xcadams** [comment]
this will be addressed with https://github.com/livepeer/explorer/issues/115, closing in favor of that issue
