### ISSUE TITLE
Show up/down status of transcoder on explorer/transcoders page

### ISSUE THREAD

**Issue by darkdarkdragon** [livepeer/explorer#75]
**What's the problem? (required)**
No information if transcoder is up or down.

**What's the current behavior? (required)**
Just no information.

**Describe a possible solution you've considered (optional)**
Explorer should periodically ping transcoder node (via http request) and show transcoder's status (up or down) in transcoders list.

**Comment by 0xcadams** [comment]
This should have been addressed with the latest explorer with reward calls and an X next to the O page w/ reward, please reopen if it is still an issue!
